name: "build"

on: ["push", "pull_request"]

jobs:
  cargo-build:
    strategy:
      matrix:
        include:
          - os: "ubuntu-latest"
            executable: "pitr_tool"
          - os: "windows-latest"
            executable: "pitr_tool.exe"

    runs-on: "${{ matrix.os }}"

    steps:
    - uses: "actions/checkout@v2"

    - uses: "actions-rs/toolchain@v1"
      with:
        toolchain: "stable"

    - uses: "actions-rs/cargo@v1"
      with:
        command: "build"
        args: "--release"

    - uses: "actions/upload-artifact@v2"
      with:
        name: "executable (${{ matrix.os }})"
        path: "target/release/${{ matrix.executable }}"
