name: "build"

on: ["push", "pull_request"]

jobs:
  cargo-build:
    runs-on: "ubuntu-latest"

    steps:
    - uses: "actions/checkout@v2"

    - uses: "actions-rs/toolchain@v1"
      with:
        toolchain: "stable"

    - uses: "actions-rs/cargo@v1"
      with:
        command: "build"
        args: "--release"

    - uses: "actions/upload-artifact@v2"
      with:
        name: "executable"
        path: "target/release/pitr_tool"
